---
name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: read

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - run: go version

      - run: make install
        name: Install dependencies

      - run: make test
        name: Execute all tests

      - uses: codecov/codecov-action@v2
        name: codecov-umbrella
        with:
          files: ./.ignore/coverage.txt
          verbose: true
          flags: unittests,spec
