---
name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: read

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - run: go version

      - name: Install dependencies
        run: make install

      - name: Execute unit tests
        run: |
          export TERM=xterm 
          make test

      - name: Execute End-to-end tests only
        run: |
          export TERM=xterm 
          make test-e2e

      - uses: codecov/codecov-action@v2
        name: codecov-umbrella
        with:
          files: ./.ignore/coverage.txt
          verbose: true
          flags: unittests,spec
