---
name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: read

jobs:
  test:
    name: Unit Test
    strategy:
      matrix:
        go: ["1.20.x"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - run: make test
        name: all test

      - uses: codecov/codecov-action@v2
        name: codecov-umbrella
        with:
          files: ./.ignore/coverage.txt
          verbose: true
          flags: unittests,spec
